Roll llvm-project from 6e11ed52057f to 0c6bf90b568f (17 revisions)
https://chromium.googlesource.com/external/github.com/llvm/llvm-project.git/+log/6e11ed52057f..0c6bf90b568f

2020-06-26 aeubanks@google.com [NewPM][BasicAA] Rename basicaa -> basic-aa, add alias
2020-06-26 sam.mccall@gmail.com [clangd] Fix test compile with GCC (name conflict)
2020-06-26 maskray@google.com [CMake] Add optional asan & safestack dependencies to DEBUGINFO_TEST_DEPS
2020-06-26 michael.hliao@gmail.com [InferAddressSpaces] Handle the pair of `ptrtoint`/`inttoptr`.
2020-06-26 maskray@google.com [debuginfo-tests] Require "lldb" for some dexter tests
2020-06-26 aemerson@apple.com [AArch64][GlobalISel] Fix extended shift addressing mode selection not handling sxth.
2020-06-26 jonas@devlieghere.com [lldb/ScriptInterpreter] Fix Windows error C2371: 'pid_t': redefinition
2020-06-25 maskray@google.com [CMake] Add llvm-config to DEBUGINFO_TEST_DEPS
2020-06-25 joker.eph@gmail.com Remove references to the 4.0 release as a major breaking (NFC)
2020-06-25 stevenwu@apple.com [compiler-rt] Add support for arm64 macOS
2020-06-25 ldionne@apple.com [libc++] Add missing <stddef.h> include to <wchar.h>
2020-06-25 ditaliano@apple.com [test] XFail TestStepNoDebug based on arch rather than OS
2020-06-25 ditaliano@apple.com [test] XFail TestSigtrampUnwind based on arch rather than OS
2020-06-25 ditaliano@apple.com [lldb/test] XFAIL TestHWBreakMultiThread on arch rather platform.
2020-06-25 ditaliano@apple.com [lldb/test] Skip TestBreakpointThumbCodesection on arm64.
2020-06-25 sunfish@mozilla.com [WebAssembly] Add warnings for -shared and -pie
2020-06-25 aardappel@gmail.com [WebAssembly] Adding 64-bit versions of __stack_pointer and other globals

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/llvm-project-emscripten-releases
Please CC wasm-waterfall@grotations.appspotmail.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md

Tbr: wasm-waterfall@grotations.appspotmail.com
Change-Id: I272c023a90314a95b579ee0837fcdc861297a527
Reviewed-on: https://chromium-review.googlesource.com/c/emscripten-releases/+/2268843
Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>