Roll llvm-project from 801d823bdec1 to 052c962ced71 (9 revisions)
https://chromium.googlesource.com/external/github.com/llvm/llvm-project.git/+log/801d823bdec1..052c962ced71

2020-06-02 dominik.montada@hightec-rt.com [GlobalISel] Combine scalar unmerge(trunc)
2020-06-02 dominik.montada@hightec-rt.com [NFC] Move vector unmerge(trunc) combine to function
2020-06-02 higuoxing@gmail.com [ObjectYAML][DWARF] Let `dumpPubSection` return `DWARFYAML::PubSection`.
2020-06-02 ravishankarm@google.com [mlir][SCFToGPU] Remove conversions from scf.for to gpu.launch.
2020-06-02 maskray@google.com [ELF] --wrap: don't error `undefined reference to __real_foo` (--no-allow-shlib-undefined) if foo is a wrapped definition
2020-06-02 yrouban@azul.com [BrachProbablityInfo] Proportional distribution of reachable probabilities
2020-06-02 richard@metafoo.co.uk Fix violations of [basic.class.scope]p2.
2020-06-02 craig.topper@gmail.com [X86] Fix a few recursivelyDeleteUnusedNodes calls that were trying to delete nodes before their user was really gone.
2020-06-02 yrouban@azul.com [BrachProbablityInfo] Rename loop variables. NFC

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/llvm-project-emscripten-releases
Please CC wasm-waterfall@grotations.appspotmail.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md

Tbr: wasm-waterfall@grotations.appspotmail.com
Change-Id: Ib777940f4850dfbf9fe8533004d9c418086cd711
Reviewed-on: https://chromium-review.googlesource.com/c/emscripten-releases/+/2226458
Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>