Roll llvm-project from 4d434f76967f to 87a14216cd40 (6 revisions)
https://chromium.googlesource.com/external/github.com/llvm/llvm-project.git/+log/4d434f76967f..87a14216cd40

2023-08-20 joker.eph@gmail.com Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'
2023-08-20 joker.eph@gmail.com Revert "Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'"
2023-08-20 joker.eph@gmail.com Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'
2023-08-20 flo@fhahn.com [LV] Move induction ::execute impls to VPlanRecipes.cpp (NFC).
2023-08-20 rahmanl@google.com [Propeller] Deprecate Codegen paths for SHT_LLVM_BB_ADDR_MAP version 1.
2023-08-20 ivan.butygin@gmail.com [mlir][CFGToSCF] Visit subregions in CFGToSCF pass

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/llvm-project-emscripten-releases
Please CC dschuff@google.com,wasm-waterfall@grotations.appspotmail.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

Tbr: wasm-waterfall@grotations.appspotmail.com
Change-Id: I34db158342c572af45f956bd3ee45a248a536d50
Reviewed-on: https://chromium-review.googlesource.com/c/emscripten-releases/+/4796974
Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>