Roll v8 from 8ca0c3133f47 to 4c19e2b99e81 (43 revisions)
https://chromium.googlesource.com/v8/v8.git/+log/8ca0c3133f47..4c19e2b99e81

2025-09-12 leszeks@chromium.org Revert "[GC] Account for global memory in CheckIneffectiveMarkCompact"
2025-09-12 dinfuehr@chromium.org [compiler] Save link register in write barrier verification
2025-09-12 jgruber@chromium.org [maglev] Speculate on elements_kind in `new Array` constructor
2025-09-12 v8-ci-autoroll-builder@chops-service-accounts.iam.gserviceaccount.com Update fuzztest (trusted)
2025-09-12 v8-ci-autoroll-builder@chops-service-accounts.iam.gserviceaccount.com Update V8 DEPS (trusted)
2025-09-12 zhijin.zeng@spacemit.com [riscv] Fix compilation error and disassembling error when enabling the RISC-V C extension
2025-09-11 manishearth@google.com [temporal] Use gn path for //third_party/icu
2025-09-11 romandvornov@microsoft.com [cdp] Add stackDepth parameter for HeapProfiler.startSampling
2025-09-11 etiennep@chromium.org [GC] Account for global memory in CheckIneffectiveMarkCompact
2025-09-11 manishearth@google.com [temporal] zoneinfo64 support for Temporal
2025-09-11 manishearth@google.com Update third_party/rust
2025-09-11 jkummerow@chromium.org [wasm-custom-desc] Catch up with upstream proposal
2025-09-11 v8-ci-autoroll-builder@chops-service-accounts.iam.gserviceaccount.com Update V8 DEPS (trusted)
2025-09-11 bikineev@chromium.org AB: Fix possiblity of PA metadata being stored inlined
2025-09-11 mic.besace@gmail.com [heap] Fix build on latest Apple Clang
2025-09-11 rezvan@chromium.org [for-of-performance] Check for Smi on iterator result
2025-09-11 mfarazma@ibm.com PPC/s390: Throw TypeError with detailed error message
2025-09-11 leszeks@chromium.org [ignition] Add expectation tests for SetPrototypeProperties
2025-09-11 victorgomes@chromium.org Revert "[maglev][optimizer] Constant fold int32 operations"
2025-09-11 nikolaskaipel@google.com [wasm][fuzzer] Store memory and global traces for differential fuzzing
2025-09-11 mlippautz@chromium.org Revert "Reland "[GC] Increase heap max_global_memory_size""
2025-09-11 victorgomes@chromium.org [maglev][optimizer] Constant fold int32 operations
2025-09-11 victorgomes@chromium.org [maglev] Do not emit nodes that can eager deopt
2025-09-11 pthier@chromium.org [regexp][arm64] Optimize SkipUntilOneOfMasked
2025-09-11 jkummerow@chromium.org [bigint][sandbox] Harden more against concurrent modification
2025-09-11 marja@chromium.org [cleanup|maglev] Clean up use_repr_hints
2025-09-11 rherouart@chromium.org [maglev][turbofan] Make Optimization Levels Reachable
2025-09-11 dmercadier@chromium.org [turbolev] Allow inlining functions with new.target
2025-09-11 saralin@google.com Add mfloat_abi flag
2025-09-11 mlippautz@chromium.org [runtime] Use faster object creation from JSON parser
2025-09-11 manoskouk@chromium.org [wasm][compilation-hints] Fix two issues
2025-09-11 victorgomes@chromium.org [maglev][kna] Support resumable loops unreachable by forward edge
2025-09-11 victorgomes@chromium.org [fuzz] Remove --additive-safe-int-feedback to fuzzers
2025-09-11 floitsch@rivosinc.com [riscv] Throw TypeError with detailed error message
2025-09-11 victorgomes@chromium.org [maglev] SBXCHECK input count is less than max allowed
2025-09-11 victorgomes@chromium.org [maglev] Enable Maglev truncation pass
2025-09-11 leszeks@chromium.org Reland "[heap] Refine ephemeron key processing"
2025-09-11 victorgomes@chromium.org [maglev] Fix inlining loop
2025-09-11 jgruber@chromium.org [maglev] Add support for multi-argument Array constructor
2025-09-11 machenbach@chromium.org Revert "[heap] Refine ephemeron key processing"
2025-09-11 yahan@iscas.ac.cn [riscv] Fix build for v8_enable_external_code_space
2025-09-11 yahan@iscas.ac.cn [riscv][wasmfx][jspi] Allow JSPI to suspend multiple stacks at once
2025-09-11 seokho@chromium.org Throw TypeError with detailed error message

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/v8-emscripten-releases
Please CC dschuff@google.com,wasm-waterfall@grotations.appspotmail.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://issues.skia.org/issues/new?component=1389291&template=1850622

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

Tbr: wasm-waterfall@grotations.appspotmail.com
Change-Id: Ib3306cab5d6d09ee2ac4a51a629fea123178b874
Reviewed-on: https://chromium-review.googlesource.com/c/emscripten-releases/+/6942197
Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>