Roll llvm-project from f1252f539ca2 to 1e85e5abb327 (37 revisions)
https://chromium.googlesource.com/external/github.com/llvm/llvm-project.git/+log/f1252f539ca2..1e85e5abb327

2025-02-24 sbc@chromium.org [clang][WebAssembly] Always have `-pthread` imply `--shared-memory` linker flag (#127939)
2025-02-24 kristof.beyls@arm.com [BOLT] pacret-scanner: fix regression test failure (#128576)
2025-02-24 vitalybuka@google.com Revert "[llvm-mt] Use XmlDeleter to free xmlFreeDoc" (#128578)
2025-02-24 zequanwu@google.com Revert "Symbolize line zero as if no source info is available (#124846)"
2025-02-24 vitalybuka@google.com [llvm-mt] Use XmlDeleter to free xmlFreeDoc (#128472)
2025-02-24 joker.eph@gmail.com Revert "[mlir] Fix integration test when `%host_cc` path contains spaces" (#128573)
2025-02-24 llvmgnsyncbot@gmail.com [gn build] Port 988480323d5e
2025-02-24 kristof.beyls@arm.com [BOLT] pacret-scanner: fix regression tests... (#128565)
2025-02-24 rniwa@webkit.org [alpha.webkit.UnretainedLocalVarsChecker] Add a checker for local variables to NS and CF types. (#127554)
2025-02-24 jonas@devlieghere.com [lldb-dap] Refactor custom & testing related request handlers (NFC) (#128549)
2025-02-24 zeratul976@hotmail.com [clang][NFC] Remove CXXRecordDecl::lookupDependentName() and its helpers (#128392)
2025-02-24 mikhail@igalia.com [SLP] Add test for getSpillCost fix
2025-02-24 sarahspall@microsoft.com [HLSL] Allow arrays to be returned by value in HLSL (#127896)
2025-02-24 llvmgnsyncbot@gmail.com [gn build] Port 82264d23a1cc
2025-02-24 jonas@devlieghere.com [lldb-dap] Refactor stepping related request handlers (NFC) (#128453)
2025-02-24 sumanth.gundapaneni@amd.com [AMDGPU] Update PromoteAlloca to handle GEPs with variable offset. (#122342)
2025-02-24 akaylor@nvidia.com [CIR] Add cir-opt tool to exercise CIR dialect parsing (#128254)
2025-02-24 bigcheesegs@gmail.com [clang] Improve module out of date error message (#128103)
2025-02-24 ramkumar.ramachandra@codasip.com [LV] Restrict widest induction type to be IntegerType (NFC) (#128173)
2025-02-24 malavika.samak@gmail.com [Wunsafe-buffer-usage] False positives for & expression indexing constant size array (arr[anything & 0]) (#112284)
2025-02-24 szakharin@nvidia.com Revert "[flang] Set LLVM specific attributes to fir.call's of Fortran runtime. (#128093)"
2025-02-24 szakharin@nvidia.com Revert "[flang] Workaround build failure."
2025-02-24 szakharin@nvidia.com [flang] Workaround build failure.
2025-02-24 llvmgnsyncbot@gmail.com [gn build] Port 850b49297615
2025-02-24 llvmgnsyncbot@gmail.com [gn build] Port 363bfd6090b0
2025-02-24 jonas@devlieghere.com [lldb-dap] Fix error C2065: 'PATH_MAX': undeclared identifier
2025-02-24 adeodhar@nvidia.com [NVPTX] Support for memory orderings for cmpxchg (#126159)
2025-02-24 thakis@chromium.org [gn build] Port d0e37d972331 (llvm-dap tweaks)
2025-02-24 tromey@adacore.com Add DISubrangeType (#126772)
2025-02-24 バレンタイン クレメン [flang][cuda][NFC] Remove shared alloc addr space (#128535)
2025-02-24 craig.topper@sifive.com [CodeGen] Change copyPhysReg interface to use Register instead of MCRegister. (#128473)
2025-02-24 harjohn@google.com [lldb-dap] skip TestDAP_server on windows to unblock CI. (#128278)
2025-02-24 craig.topper@sifive.com [RISCV] Remove unnecessary entries from RISCVVInversePseudosTable. NFC (#128376)
2025-02-24 craig.topper@sifive.com [SPIRV] Stop including SPIRVInstrInfo.h in MCTargetDesc. NFC (#128443)
2025-02-24 cheung.deric@gmail.com [test] Remove `-emit-llvm` from the `and-errors.hlsl` test to avoid writing to a potentially write-protected directory (#128047)
2025-02-24 szakharin@nvidia.com [flang] Set LLVM specific attributes to fir.call's of Fortran runtime. (#128093)
2025-02-24 roberthoodchatham@gmail.com [object][WebAssembly] Add support for RUNTIME_PATH to yaml2obj and obj2yaml (#126080)

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/llvm-project-emscripten-releases
Please CC dschuff@google.com,wasm-waterfall@grotations.appspotmail.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://issues.skia.org/issues/new?component=1389291&template=1850622

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

Tbr: wasm-waterfall@grotations.appspotmail.com
Change-Id: Ic5a5a8a4164120fe68c05aa50b9935a7e89504f3
Reviewed-on: https://chromium-review.googlesource.com/c/emscripten-releases/+/6300513
Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>